;Author
;JUNAID AHMED GHAURI

.MODEL SMALL
.STACK 100

.DATA
	S1 DB "Enter any digit (0--9) :$"
	S2 DB 0DH,0AH,"***VALUES ARE SAVED ACCORING TO TASK IN REGISTERS***$"

.CODE
MAIN PROC
	MOV AX,@DATA		;giving segment 
	MOV DS,AX	
	
        MOV AH,09H
	MOV DX,OFFSET S1	;prompt user 
	INT 21H
	
	MOV AH,01H		;take input
	INT 21H

	MOV CL,AL 		;SAVE INPUT 
	MOV CH,00H
	SUB CL,48D		;CHANGE IN TO NUMBER
	
	MOV BH,00H
	MOV BL,01D
	SAL BX,CL		;2POWER N IN TO BX
	

	
	MOV CL,02D		;DIVIDE BX BY 4
	SHR BX,CL


	MOV DX,BX		;TAKE COMPLEMENT OF BX AND SAVE IN DX
	XOR DX,0FFFFH

	MOV AH,09H
	MOV DX,OFFSET S2	;MESSAGE 
	INT 21H

	MOV AH,4CH		;exit
        INT 21H
MAIN ENDP			;end procedure
END MAIN			;end main
